name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package.json
      - name: Install dependencies
        working-directory: backend
        run: npm install
      - name: Lint
        working-directory: backend
        run: npm run lint -- --max-warnings=0
      - name: Unit tests
        working-directory: backend
        run: npm test -- --ci --runInBand
      - name: E2E tests
        working-directory: backend
        run: npm run test:e2e -- --runInBand
      - name: Build
        working-directory: backend
        run: npm run build
