apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  NODE_ENV: "production"
  PORT: "4000"
  REDIS_HOST: "redis.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  QDRANT_URL: "http://qdrant.infra.svc.cluster.local:6333"
  MINIO_ENDPOINT: "http://minio.infra.svc.cluster.local:9000"
