apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: backend
data:
  NEXT_PUBLIC_API_URL: "https://api.health-tourism.local"
  NEXT_PUBLIC_ORCHESTRATOR_URL: "https://orchestrator.health-tourism.local"
