apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
